--- #YAML:1.0
name: UNIVERSAL-canAUTOLOAD
version: 0.01
license: perl
distribution_type: module
requires:
  Class::ISA: 0
  Test::More: 0
recommends: {}
build_requires: {}
conflicts: {}
provides:
  UNIVERSAL::canAUTOLOAD:
    file: lib/UNIVERSAL/canAUTOLOAD.pm
    version: 0.01
generated_by: Module::Build version 0.21
